<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>New_Skill_Feats_and_Items</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <NoWarn>1998;NETSDK1206;NU1901;NU1902;NU1903;NU1904;VSTHRD200</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Common">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Common.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury Days">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\Dawnsbury Days.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>D:\SteamLibrary\steamapps\common\Dawnsbury Days\Data\MonoGame.Framework.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
